name: Daily Stock Analysis

on:
  schedule:
    - cron: '15 4 * * *'  # 9:45 AM IST (4:15 AM UTC)
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget

    - name: Install TA-Lib from Ubuntu repository (stable)
      run: |
        sudo apt-get install -y libta-lib-dev
        sudo ldconfig

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install --no-cache-dir --upgrade pip
        pip install --no-cache-dir numpy
        pip install --no-cache-dir TA-Lib==0.4.24  # Specific version that works with system lib
        pip install --no-cache-dir -r requirements.txt

    - name: Verify TA-Lib installation
      run: |
        python -c "import talib; print(f'TA-Lib version: {talib.__version__}')"

    - name: Run analysis
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: python niftybees_strategy.py
