name: NIFTYBEES Daily Analysis

on:
  schedule:
    # Runs at 2:30 PM IST daily (09:00 UTC)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVERS: ${{ secrets.EMAIL_RECEIVERS }}
      run: python niftybees_strategy.py
    
    - name: Archive results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: analysis-log
        path: niftybees_trades.log
